# OMEN Configuration File
# Open Model Exchange Network - Universal AI API Gateway

[server]
bind = "0.0.0.0"
port = 8080
workers = 4
timeout_seconds = 30

[storage]
db = "sqlite:///data/omen.db"
# redis = "redis://localhost:6379"

[routing]
prefer_local_for = ["code", "regex", "tests"]
budget_monthly_usd = 150.0
auto_swap = false

# Soft limits per provider (USD)
[routing.soft_limits]
anthropic = 70.0
openai = 70.0

# Provider configurations
[providers.openai]
enabled = false
# api_key = "sk-..."  # Set via OMEN_OPENAI_API_KEY
# base_url = "https://api.openai.com/v1"
timeout_seconds = 30
models = ["gpt-4", "gpt-4-turbo", "gpt-3.5-turbo"]

[providers.anthropic]
enabled = false
# api_key = "sk-ant-..."  # Set via OMEN_ANTHROPIC_API_KEY
# base_url = "https://api.anthropic.com"
timeout_seconds = 30
models = ["claude-3-opus-20240229", "claude-3-sonnet-20240229", "claude-3-haiku-20240307"]

[providers.google]
enabled = false
# api_key = "..."  # Set via OMEN_GOOGLE_API_KEY
timeout_seconds = 30

[providers.ollama]
enabled = false
endpoints = ["http://localhost:11434"]
timeout_seconds = 30
models = ["llama3:8b", "deepseek-coder:6.7b", "qwen2.5:7b"]

[providers.azure]
enabled = false
# endpoint = "https://your-resource.openai.azure.com/"  # Set via OMEN_AZURE_OPENAI_ENDPOINT
# api_key = "..."  # Set via OMEN_AZURE_OPENAI_API_KEY
api_version = "2024-02-15-preview"
timeout_seconds = 30

[providers.xai]
enabled = false
# api_key = "xai-..."  # Set via OMEN_XAI_API_KEY
# base_url = "https://api.x.ai/v1"
timeout_seconds = 30

[auth]
require_api_key = false
# master_key = "..."  # Set via OMEN_MASTER_KEY

[logging]
level = "info"
enable_access_logs = true